services:
  yolov9:
    build:
      context: .
      dockerfile: Dockerfile
    image: yolov9-football:latest
    container_name: yolov9
    runtime: nvidia  # Use NVIDIA runtime
    volumes:
      - ~/yolov9:/yolov9
     # - /tmp/.X11-unix:/tmp/.X11-unix  # Mount X11 socket for OpenCV GUI, no use if the device does not support GUI
     # - ~/yolov9/sports/examples/soccer/notebooks/datasets/football-players-detection-10/:/coco/
    shm_size: 16g
    tty: true
    stdin_open: true
    environment:
     # - DISPLAY=$DISPLAY
      - NVIDIA_VISIBLE_DEVICES=all
