services:
  yolov9:
    build:
      context: .
      dockerfile: Dockerfile
    image: yolov9-football:latest
    container_name: yolov9_football
    runtime: nvidia  # Use NVIDIA runtime
    volumes:
      - ~/football-yolov9:/yolov9-main
     # - /tmp/.X11-unix:/tmp/.X11-unix  # Mount X11 socket for OpenCV GUI, no use if the device does not support GUI
    shm_size: 32g
    tty: true
    stdin_open: true
    environment:
     # - DISPLAY=$DISPLAY
      - NVIDIA_VISIBLE_DEVICES=all
      - NVIDIA_DRIVER_CAPABILITIES=all  # Request all capabilities
    deploy:  # Alternative to "runtime: nvidia" for newer Docker versions
      resources:
        reservations:
          devices:
            - driver: nvidia
              count: all
              capabilities: [gpu, utility, compute, video]